// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsghzuwjztbnciaeywkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZ2h6dXdqenRibmNpYWV5d2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDM3OTksImV4cCI6MjA3MDQ3OTc5OX0.Ytdn241opUfI6xPD6467jC1Noekt1-ZpuMkey5YbNYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});